<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>gtec_mmwave_reader</name>
  <version>1.0.0</version>
  <description>The gtec_mmwave_reader package</description>

  <maintainer email="valentin.barral@udc.es">Valentin Barral</maintainer>
  <license>MIT</license>

  <!-- Dependencias de compilación y ejecución -->
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>radar_msgs</depend>
  <depend>rclpy</depend>

  <exec_depend>python3-regex</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
